### PR TITLE
CentOS 7 compatibility

### PR DESCRIPTION
**Pull request by tangestani**
The version of augeasproviders that this project is dependent on uses grub as the kernel_parameter provider instead of grub2 if none is specified.

### CODE REVIEW

**Comment by tangestani** [comment]
I've noticed that this module no longer exists Puppet Forge. Are you still maintaining it?

**Comment by treydock** [comment]
@tangestani This module never made it to the forge.  I still use it in production and it's one of the modules I'd like to release on the Puppet Forge after a slight refactor of a few things.  The changes look good. I'll go over them more carefully tomorrow and merge them before I finalize this module for the forge.

**Comment by treydock** [comment]
@tangestani Can you please rebase your commits?  It appears your changes don't incorporate the changes I made some time ago to add the `enable` parameter.

**Comment by sammcj** [comment]
Any update on this?

**Comment by treydock** [comment]
Merged, thanks for the contribution.

**Pull request merged**
